openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-qh82.onrender.com

tags:
  - name: Contacts
    description: Contacts management

paths:
  /contacts:
    $ref: ../swagger/paths/contacts/index.yaml
  /contacts/{contactId}:
    $ref: ../swagger/paths/contacts/{contactId}/index.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Contact:
      type: object
      properties:
        _id: { type: string, description: Mongo ObjectId }
        name: { type: string }
        phoneNumber: { type: string }
        email: { type: [string, 'null'], format: email }
        contactType: { type: string, enum: [home, work, other] }
        isFavourite: { type: boolean }
        photo: { type: [string, 'null'], description: Cloudinary secure_url }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
      required: [_id, name, phoneNumber, contactType, isFavourite]

    ContactCreate:
      type: object
      required: [name, phoneNumber, contactType]
      properties:
        name: { type: string, minLength: 3, maxLength: 20 }
        phoneNumber: { type: string, minLength: 3, maxLength: 20 }
        email: { type: [string, 'null'], format: email }
        contactType: { type: string, enum: [home, work, other] }
        isFavourite: { type: boolean, default: false }

    ContactUpdate:
      type: object
      properties:
        name: { type: string }
        phoneNumber: { type: string }
        email: { type: [string, 'null'], format: email }
        contactType: { type: string, enum: [home, work, other] }
        isFavourite: { type: boolean }

    Error:
      type: object
      required: [status, message]
      properties:
        status: { type: integer }
        message: { type: string }
